name: Test Push

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          date > deneme.txt

          git add deneme.txt
          git commit -m "Test push"

          git push