name: Update Fuel Prices

on:
  schedule:
    # Her gün 05:00 UTC = Türkiye saatiyle yaklaşık 08:00
    - cron: "0 5 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
        working-directory: server

      - run: node updateFuel.js
        working-directory: server

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update fuel prices"
          file_pattern: server/fuel.json